services:
  - type: web
    name: webhook-swiss-army-knife
    runtime: go
    plan: free
    buildCommand: go build -trimpath -ldflags="-s -w" -o bin/server ./cmd/server
    startCommand: ./bin/server
    healthCheckPath: /healthz
    autoDeployTrigger: commit
